fujidaiti/smooth_sheets

.github/workflows/dry_publish.yaml
=> Use `release/*` for the branch name pattern that trigger dry_publish workflow

package/analysis_options.yaml, package/lib/src/draggable/draggable_sheet.dart, package/lib/src/draggable/sheet_draggable.dart, package/lib/src/foundation/framework.dart, package/lib/src/foundation/sheet_activity.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/foundation/sheet_physics.dart, package/lib/src/navigation/navigation_sheet.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart
Fixes #22. Unfortunately, there are still some problems related to the keyboard (e.g. #14) that will be taken care of in a future PR.
Summary:
- Added `SheetExtent.settle`, which causes the sheet to settle into a stationary position similar to the `goBallistic(0.0)`, but with a constant (non zero) and relatively high velocity.
- Added `SheetActivity.didFinalizeDimensions`, which is called once in a frame after all measurement processes for both the content and the viewport size have been completed.
=> Improve the sheet motion while opening/closing the keyboard

package/lib/src/modal/cupertino.dart, package/lib/src/modal/modal_sheet.dart
=> Add `settings` and `fullscreenDialog` params to the constructors of modal sheet routes and pages

cookbook/ios/Runner.xcodeproj/project.pbxproj, cookbook/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, cookbook/lib/showcase/ai_playlist_generator.dart, cookbook/lib/showcase/airbnb_mobile_app.dart, cookbook/lib/showcase/safari/menu.dart, cookbook/lib/tutorial/cupertino_modal_sheet.dart, cookbook/lib/tutorial/scrollable_sheet.dart, cookbook/lib/tutorial/sheet_content_scaffold.dart, cookbook/lib/tutorial/sheet_controller.dart, cookbook/lib/tutorial/sheet_draggable.dart, cookbook/lib/tutorial/sheet_physics.dart, package/lib/src/draggable/sheet_draggable.dart, package/lib/src/foundation/sheet_activity.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/foundation/sheet_physics.dart, package/lib/src/internal/double_utils.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/lib/src/scrollable/scrollable_sheet_physics.dart, package/test/foundation/sheet_physics_test.dart
Closes #20, closes #29.
- Added `SnapToNearestEdge`, a `SheetSnappingBehavior` that snaps to the nearest edge either `minPixels` or `maxPixels`.
- Added convenient getters to `MaybeSheetMetrics`, `isPixelsInBounds` and `isPixelsOutOfBounds`.
- Added `ScrollableSheetPhysics` as the replacement for the deleted `SnapToNearest.maxFlingVelocityToSnap` property.
- Made `SnapToNearest` aware of fling gestures.
- Deleted `SnapToNearest.maxFlingVelocityToSnap`.
- `SnapToNearest` can no longer be a `const`, in exchange for performance improvement.
Due to the above reason, `SnapToNearestEdge` has been used as the default value for `SnappingSheetPhysics.snappingBehavior` instead of `SnapToNearest`.
=> Physics improvements

.github/workflows/code_check.yml, .github/workflows/unit_testing.yaml, package/test/foundation/sheet_physics_test.dart
=> Add unit testing workflow

.github/workflows/code_check.yaml
`dorny/paths-filter` fails if it runs on the default branch (`main`) with no checkout step.
=> Add missing checkout

.github/workflows/code_check.yaml, cookbook/lib/showcase/ai_playlist_generator.dart, cookbook/lib/showcase/safari/actions.dart, cookbook/lib/showcase/safari/menu.dart, cookbook/lib/showcase/todo_list/todo_editor.dart, cookbook/lib/tutorial/declarative_modal_sheet.dart, cookbook/lib/tutorial/imperative_modal_sheet.dart, package/lib/src/modal/cupertino.dart, package/lib/src/modal/modal_sheet.dart
Closes #18.
- Add `SheetDismissible`, which enables the enclosed sheet to be dismissed by a drag-down gesture. It accepts an `onDismiss` callback, which will be invoked when the user tries to dismiss the sheet by dragging it down, providing an opportunity to determine if the sheet should be dismissed.
- Add tutorial code for `SheetDismissible`.
- Update the Safari and the AI playlist generator example to use `SheetDismissible` to show a confirmation dialog to discard changes.
- Remove `ModalSheetRouteMixin.enablePullToDismiss`.
=> Add conditional modal sheet popping feature

package/lib/src/modal/cupertino.dart
Removed `enablePullToDismiss` from `CupertinoModalSheetPage` as it is no longer in use.
=> Remove `enablePullToDismiss`

package/CHANGELOG.md, package/README.md, package/lib/src/draggable/draggable_sheet.dart, package/lib/src/draggable/sheet_draggable.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/foundation/sized_content_sheet.dart, package/lib/src/navigation/navigation_routes.dart, package/lib/src/scrollable/scrollable_sheet.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/pubspec.yaml
- Add doc comments to `sheet_extent.dart`.
- Avoid using GitHub alert syntax. (Fixes #23)
- Rename `SingleChildSheet*` to `SizedContentSheet*`.
=> Documentation updates

.github/workflows/publish.yaml
Fixes #47. Based on the [documentation](https://dart.dev/tools/pub/automated-publishing#configuring-a-github-action-workflow-for-publishing-to-pub-dev), it appears that using `dart-lang/setup-dart@v1` is necessary in the publishing workflow to resolve the authentication issue.
> The workflow authenticates to pub.dev using a temporary [GitHub-signed OIDC token](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect), the token is created and configured in the dart-lang/setup-dart step. To publish to pub.dev, subsequent steps can run dart pub publish --force.
=> Reland "Fix publish workflow"

package/CHANGELOG.md, package/lib/src/foundation/sheet_activity.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/foundation/sheet_status.dart, package/lib/src/modal/modal_sheet.dart, package/lib/src/navigation/navigation_route.dart, package/lib/src/navigation/navigation_sheet.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/pubspec.yaml, package/test/foundation/sheet_physics_test.dart
This PR fixes #54.
A modal sheet can now be dismissed by clicking the barrier ONLY when its status is `SheetStatus.stable` and the pull-to-dismiss action is not running.
=> Prevent modal sheet from poping while dragging

cookbook/lib/showcase/ai_playlist_generator.dart, cookbook/lib/showcase/todo_list/todo_editor.dart, cookbook/lib/tutorial/keyboard_dismiss_behavior.dart, cookbook/lib/tutorial/sheet_content_scaffold.dart, docs/migration-guide-0.3.x.md, docs/migration-guide-0.4.x.md, package/CHANGELOG.md, package/README.md, package/analysis_options.yaml, package/lib/src/foundation/sheet_content_scaffold.dart, package/lib/src/foundation/sheet_extent.dart, package/pubspec.yaml
This PR closes #15 and closes #19.
**New Features**
- Added the `BottomBarVisibility` widgets, which can be used to flexibly control the visibility of the scaffold's bottom bar based on the sheet position.
- Added the `ResizeScaffoldBehavior`, which is a more flexible version of the `SheetContentScaffold.resizeToAvoidBottomInset` property.
**Breaking Changes**
- Removed the `requiredMinExtentForStickyBottomBar` property from the scaffold with the introduction of `BottomBarVisibility`.
- Removed the `resizeToAvoidBottomInset` property from the scaffold and added the `resizeBehavior` property as a replacement.
**Misc**
- Bumped the package version to 0.4.0.
- Added the migration guide from 0.3.x to 0.4.x.
- Mention the `BottomBarVisibility` widgets in the README.
=> Make bottom bar visibility more customizable

package/CHANGELOG.md, package/lib/src/foundation/sheet_content_scaffold.dart, package/pubspec.yaml
Fix mistakes in the documentation of `BottomBarVisibility` and `ConditionalStickyBottomBarVisibility` which may mislead readers.
=> Fix mistakes in documentation

package/lib/smooth_sheets.dart, package/lib/src/internal/into.dart, package/lib/src/scrollable/content_scroll_position.dart, package/lib/src/scrollable/delegatable_scroll_position.dart, package/lib/src/scrollable/scrollable_sheet.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/lib/src/scrollable/scrollable_sheet_physics.dart
This PR reworks some of the guts of the ScrollableSheet in preparation for #87.
=> Refactor scrollable module to prepare for upcoming features

package/lib/smooth_sheets.dart, package/lib/src/foundation/sized_content_sheet.dart, package/lib/src/foundation/theme.dart, package/lib/src/navigation/navigation_sheet.dart
=> Add SheetTheme

package/lib/src/draggable/draggable_sheet.dart, package/lib/src/foundation/physics.dart, package/lib/src/foundation/theme.dart, package/lib/src/navigation/navigation_routes.dart, package/lib/src/scrollable/scrollable_sheet.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/lib/src/scrollable/scrollable_sheet_physics.dart, package/test/foundation/physics_test.dart
The following APIs are added in this PR to enable specifying the default physics and the default ancestor physics that is used by sheets.
- `SheetPhysics.applyTo`
- `SheetPhysics.copyWith`
- `SheetTheme.physics`
- `SheetTheme.basePhysics`
=> Add a way to specify default physics and default ancestor physics

cookbook/lib/showcase/airbnb_mobile_app.dart, cookbook/lib/tutorial/bottom_bar_visibility.dart, cookbook/lib/tutorial/sheet_content_scaffold.dart, cookbook/lib/tutorial/sheet_controller.dart, docs/migration-guide-0.5.x.md, package/CHANGELOG.md, package/README.md, package/lib/smooth_sheets.dart, package/lib/src/draggable/draggable_sheet.dart, package/lib/src/foundation/activities.dart, package/lib/src/foundation/animations.dart, package/lib/src/foundation/framework.dart, package/lib/src/foundation/notifications.dart, package/lib/src/foundation/physics.dart, package/lib/src/foundation/sheet_content_scaffold.dart, package/lib/src/foundation/sheet_controller.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/foundation/theme.dart, package/lib/src/modal/cupertino.dart, package/lib/src/modal/modal_sheet.dart, package/lib/src/navigation/navigation_route.dart, package/lib/src/navigation/navigation_routes.dart, package/lib/src/navigation/navigation_sheet.dart, package/lib/src/scrollable/scrollable_sheet.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/pubspec.yaml, package/test/foundation/physics_test.dart
This PR has breaking changes. See `docs/migration-guide-0.5.x.md` for more details.
The summary is:
- Moved responsibility for creating SheetExtent to SheetController
- Reimplemented SheetExtent as ValueListenable<SheetMetrics>
- Changed SheetActivity to directly update SheetExtent instead of having its own `pixels`
- Refactored the core logic of NavigationSheet
- Bumped to 0.5.0
=> Reimplement core architecture

package/CHANGELOG.md, package/lib/smooth_sheets.dart, package/pubspec.yaml
=> Re-export NavigationSheetRoute unintentionally omitted in v0.5.0

package/CHANGELOG.md, package/lib/src/internal/transition_observer.dart, package/lib/src/navigation/navigation_sheet.dart, package/pubspec.yaml
=> Fix a crash during the first build of NavigationSheet with a path that contains multiple routes such as /a/b/c

package/lib/src/draggable/draggable_sheet_extent.dart, package/lib/src/foundation/activities.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/navigation/navigation_sheet.dart, package/lib/src/scrollable/scrollable_sheet.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart
`SheetExtent.takeOver` was changed to transfer the current activity from the old extent to the new extent instead of disposing of it, so that the internal state of the activity is maintained before and after changing its owner.
=> Transfer activity from old extent to new extent in takeOver()

docs/migration-guide-0.7.x.md, package/CHANGELOG.md, package/lib/src/foundation/keyboard_dismissible.dart, package/lib/src/foundation/sheet_drag.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/lib/src/scrollable/sheet_content_scroll_activity.dart, package/pubspec.yaml
Fixes #144.
- `SheetDragDetails` subclasses no longer implement `Drag*Details`
- Bumped to 0.7.0
- Added a migration guide
=> Fix: Unable to build version 0.6.0 for Flutter versions < 3.22.0

cookbook/pubspec.yaml, docs/migration-guide-0.7.x.md, package/pubspec.yaml
Increased the minimum Dart SDK version to 3.2.0 and the Flutter SDK version to 3.16.0.
=> Increase min SDK versions

cookbook/lib/tutorial/declarative_navigation_sheet.dart, cookbook/lib/tutorial/draggable_sheet.dart, cookbook/lib/tutorial/imperative_navigation_sheet.dart, cookbook/lib/tutorial/scrollable_sheet.dart, cookbook/lib/tutorial/sheet_content_scaffold.dart
Edited tutorial code to **not** put a sheet in a scaffold widget, to prevent the readers from being misled into putting a sheet in a scaffold, which can cause problems like #66.
=> Do not put sheets in scaffolds

package/CHANGELOG.md, package/analysis_options.yaml, package/lib/src/internal/transition_observer.dart, package/lib/src/navigation/navigation_route.dart, package/lib/src/navigation/navigation_sheet_extent.dart, package/pubspec.yaml, package/test/navigation/navigation_sheet_test.dart
Fixes #139.
Essentially the issue was fixed by the changes in #164, so this PR just adds some missing pieces to fully support non-`NavigationSheetRoute`s in `NavigationSheet`.
- Relaxed assertion to allow routes other than `NavigationSheetRoute`.
- Removed equals and hashCode to reduce unnecessary complexity in code.
- Implemented `canTransitionFrom` and `canTransitionTo` of `NavigationSheetRoute`.
- Added a regression test of #139.
- Disabled `unneecssary_parenthesis` rule.
- Bumped the version to 0.7.3.
=> Allow routes other than NavigationSheetRoute to be used in NavigationSheet

docs/migration-guide-0.8.x.md, package/CHANGELOG.md, package/README.md, package/lib/src/foundation/foundation.dart, package/lib/src/foundation/sheet_physics.dart
Closes #159.
- Removed the `StretchingSheetPhysics.stretchingRange` property.
- Added `StretchingBehavior` and its subclasses as the replacements.
- `FixedStretchingBehavior`: Allows a sheet to stretch by up to a fixed amount.
- `DirectionAwareStretchingBehavior`: Similar to `FixedStretchingBehavior`, but can accept different values for upward and downward directions.
- Added the migration guide.
- Updated README and CHANGELOG.
=> Make stretching behavior of StretchingSheetPhysics more customizable

cookbook/lib/showcase/ai_playlist_generator.dart, cookbook/lib/showcase/airbnb_mobile_app.dart, cookbook/lib/showcase/safari/menu.dart, cookbook/lib/tutorial/bottom_bar_visibility.dart, cookbook/lib/tutorial/cupertino_modal_sheet.dart, cookbook/lib/tutorial/extent_driven_animation.dart, cookbook/lib/tutorial/scrollable_sheet.dart, cookbook/lib/tutorial/sheet_content_scaffold.dart, cookbook/lib/tutorial/sheet_controller.dart, cookbook/lib/tutorial/sheet_draggable.dart, cookbook/lib/tutorial/sheet_physics.dart, docs/migration-guide-0.8.x.md, package/README.md, package/lib/src/foundation/foundation.dart, package/lib/src/foundation/sheet_physics.dart, package/lib/src/scrollable/scrollable_sheet_activity.dart, package/test/foundation/physics_test.dart
`StretchingSheetPhysics` was renamed to `BouncingSheetPhysics` to better reflect its behavior, as it does not change the actual height of the sheet, but rather allows its position to go beyond the content bounds. Accordingly, the other related classes and properties were also renamed.
=> Rename `stretching` to `bouncing`

.vscode/launch.json, cookbook/lib/tutorial/ios_style_declarative_modal_navigation_sheet.dart, package/CHANGELOG.md, package/README.md, package/lib/src/draggable/draggable_sheet.dart, package/lib/src/foundation/sheet_controller.dart, package/lib/src/foundation/sheet_extent_scope.dart, package/lib/src/navigation/navigation_sheet.dart, package/lib/src/scrollable/scrollable_sheet.dart, package/pubspec.yaml, package/test/draggable/draggable_sheet_test.dart, package/test/navigation/navigation_sheet_test.dart, package/test/scrollable/scrollable_sheet_test.dart
Fixes #168.
The `SheetExtentScope` has been modified to no longer rely on an inherited sheet controller as a fallback. Instead, the sheet controller is now explicitly provided in the constructor of `SheetExtentScope` when necessary.
Additional changes:
- Added a new example demonstrating an iOS-style modal NavigationSheet with go_router.
- Added  a regression test for the issue.
- Added more tests to cover the functionality around inheriting a sheet controller.
- Bumped the version number to 0.8.1.
=> Fix: Cupertino style modal transition not working with NavigationSheet

package/CHANGELOG.md, package/lib/src/foundation/sheet_activity.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/navigation/navigation_sheet_extent.dart, package/pubspec.yaml, package/test/draggable/draggable_sheet_test.dart, package/test/navigation/navigation_sheet_test.dart, package/test/scrollable/scrollable_sheet_test.dart, package/test/src/keyboard_inset_simulation.dart
Fixes #14.
The sheet position adjustment strategy of `AnimatedSheetActivity`, which is used when either the sheet content size or the viewport size changes, was modified to:
1. append the delta of `MediaQueryData.viewInsets.bottom` (the keyboard height) to keep the visual sheet position unchanged, and
3. if the animation is still running, start a new linear animation to bring the sheet position to the recalculated final position in the remaining duration. We use a linear curve here because starting a curved animation in the middle of another curved animation tends to look jerky.
=> Fix: Opening keyboard interrupts sheet animation

cookbook/lib/showcase/safari/bookmark.dart, cookbook/lib/showcase/todo_list/todo_editor.dart, cookbook/lib/tutorial/keyboard_dismiss_behavior.dart, docs/migration-guide-0.9.x.md, package/lib/src/draggable/draggable_sheet.dart, package/lib/src/foundation/keyboard_dismissible.dart, package/lib/src/navigation/navigation_sheet.dart, package/lib/src/scrollable/scrollable_sheet.dart, package/test/draggable/draggable_sheet_test.dart, package/test/navigation/navigation_sheet_test.dart, package/test/scrollable/scrollable_sheet_test.dart
None.
This PR prepares for the upcoming `SheetActivity.ignorePointer` API. In these changes, the implementation of `SheetContext` will be moved from `SheetExtentScopeState` to the State classes of each sheet widget. As a result, the `SheetKeyboardDismissible` widget will need to be an ancestor of a sheet. This is because `SheetContext.notificationContext` will be at the sheet widget itself (currently it is at `SheetExtentScope`, which is a descendant of the sheet). Consequently, the `SheetKeyboardDismissible` internally inserted into the sheet subtree won't be able to catch `SheetNotification`s, resulting in the keyboard dismissing behavior not working.
=> Prefer composition style for SheetKeyboardDismissible

package/lib/src/foundation/sheet_activity.dart, package/lib/src/foundation/sheet_extent_scope.dart, package/lib/src/foundation/sheet_viewport.dart, package/lib/src/navigation/navigation_sheet_activity.dart, package/lib/src/scrollable/scrollable_sheet_activity.dart, package/test/flutter_test_config.dart, package/test/foundation/sheet_viewport_test.dart, package/test/navigation/navigation_sheet_test.dart
Fixes #166.
This PR introduces `SheetActivity.shouldIgnorePointer`, a flag that indicates whether the sheet should prevent its content from receiving the pointer events. `TransitionSheetActivity` for `NavigationSheet` sets this flag to `true` to avoid potential issues that caused by user gestures during the unstable state of route transitions.
=> Ignore pointer

package/lib/src/foundation/sheet_activity.dart, package/lib/src/foundation/sheet_drag.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/foundation/sheet_physics.dart, package/lib/src/navigation/navigation_sheet_extent.dart, package/lib/src/scrollable/scrollable_sheet_activity.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/test/foundation/sheet_notification_test.dart
Fixes #179.
Moved the notification dispatch logic from `SheetExtent.beginActivity()` to the individual `SheetActivity` classes, as they have a better understanding of what kind of notification should be dispatched and when. This refactoring will implicitly fix #179, as the assertions that caused the errors reported in the issue have also been removed in this PR.
=> Refactor notification dispatch mechanism

package/lib/src/scrollable/scrollable_sheet_activity.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/lib/src/scrollable/sheet_content_scroll_position.dart, package/test/scrollable/scrollable_sheet_test.dart
Fixes #190.
This PR fixes an incorrect use of the `ScrollActivity.shouldIgnorePointer` flag that has caused the issue.
Previously, `DragScrollDrivenSheetActivity` used to start a `SheetContentBallisticScrollActivity` with `shouldIgnorePointer` set to `false` when a drag gesture ended. However, it should actually be `true` except in a special case. This is because setting `ScrollActivity.shouldIgnorePointer` to `true` means that clickable items in the scroll view cannot receive pointer events while performing that activity, and the scroll view may receive them instead. So if the flag is set to `false` during a ballistic scroll animation and there are any clickable items in the scroll view, the scroll view may not be able to receive the pointer events, resulting in the ballistic scroll …
=> Fix: Momentum scrolling continues despite press and hold in list view

package/CHANGELOG.md, package/lib/src/foundation/foundation.dart, package/lib/src/foundation/sheet_activity.dart, package/lib/src/foundation/sheet_drag.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/foundation/sheet_gesture_tamperer.dart, package/lib/src/foundation/sheet_notification.dart, package/lib/src/modal/modal_sheet.dart, package/lib/src/scrollable/scrollable_sheet_activity.dart, package/test/foundation/sheet_notification_test.dart
None.
In this PR, the following new features have been added:
- `SheetDragCancelNotification`, which is dispatched when a drag is canceled.
- `SheetDragCancelDetails`, which represents the final state of `SheetDragController.details` when the tracked drag gesture is canceled.
=> Dispatch a notification when drag is canceled

package/lib/src/draggable/draggable_sheet.dart, package/lib/src/draggable/draggable_sheet_extent_scope.dart, package/lib/src/foundation/sheet_context.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/foundation/sheet_extent_scope.dart, package/lib/src/navigation/navigation_route.dart, package/lib/src/navigation/navigation_routes.dart, package/lib/src/navigation/navigation_sheet.dart, package/lib/src/navigation/navigation_sheet_extent_scope.dart, package/lib/src/scrollable/scrollable_sheet.dart, package/lib/src/scrollable/scrollable_sheet_extent_scope.dart, package/test/foundation/sheet_viewport_test.dart
None.
`SheetExtentScopeState` no longer implements `SheetContext`. Instead, these implementations have been moved to `SheetContextStateMixin`, which is mixed in by all the `*SheetState` classes.
=> Refactor: Lift sheet context up

package/CHANGELOG.md, package/lib/src/foundation/sheet_context.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/foundation/sheet_physics.dart, package/lib/src/internal/double_utils.dart, package/lib/src/internal/float_comp.dart, package/lib/src/modal/cupertino.dart, package/lib/src/modal/modal_sheet.dart, package/lib/src/scrollable/scrollable_sheet_activity.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/pubspec.yaml, package/test/foundation/sheet_viewport_test.dart, package/test/scrollable/scrollable_sheet_test.dart
Fixes #207.
This PR improves floating-point value comparisons throughout the codebase to address an existing issue and prevent potential problems related to floating-point precision errors. For example, #207 was caused by infinite recursion of `SheetContentScrollPositionOwner.goBallisticWithScrollPosition` calls, triggered by `ScrollMetrics.outOfRange` always being true in `ScrollPhysics.createBallisticSimulation` due to such a floating-point precision error.
=> Fix: Sometimes touch is ignored when scrollable sheet reaches edge

.github/workflows/dry_publish.yaml
None.
After the release of Flutter 3.24, pub.dev and `pana` have started to report the following warning:
```
40/50 points: code has no errors, warnings, lints, or formatting issues
INFO: 'onPopInvoked' is deprecated and shouldn't be used. Override onPopInvokedWithResult instead. This feature was deprecated after v3.22.0-12.0.pre.
lib/src/modal/modal_sheet.dart:395:13
╷
395 │       route.onPopInvoked(didPop);
│             ^^^^^^^^^^^^
```
This decreases the package's pub points for the *Pass-static-analysis* section from 50 to 40, but the current CI requires it to always be 50, resulting in no PR passing the CI.
Although it is possible to fix this warning by following [the migration guide](https://docs.flutter.dev/release/breaking-changes/popscope-with-result), we are not doing this for …
=> Decrease required minimum pub points (tmp fix)

.vscode/launch.json, cookbook/lib/tutorial/navigation_sheet_and_keyboard.dart, package/CHANGELOG.md, package/lib/src/navigation/navigation_sheet_activity.dart, package/pubspec.yaml
- Fixes #195
Added handling logic for the software keyboard overlay on the navigation sheet.
=> Fix: Keyboard visibility changes disrupt route transition animation in NavigationSheet

.vscode/launch.json, cookbook/lib/tutorial/scrollable_pageview_sheet.dart, package/CHANGELOG.md, package/lib/src/foundation/sheet_drag.dart, package/lib/src/foundation/sheet_extent.dart, package/lib/src/foundation/sheet_status.dart, package/lib/src/scrollable/scrollable_sheet_activity.dart, package/lib/src/scrollable/scrollable_sheet_extent.dart, package/lib/src/scrollable/sheet_content_scroll_activity.dart, package/lib/src/scrollable/sheet_content_scroll_position.dart, package/pubspec.yaml, package/test/scrollable/scrollable_sheet_test.dart
Fixes #214.
This PR adds `holdWithScrollPosition()` to `ScrollableSheetExtent` to handle press-and-hold gestures in scrollable sheet content. It starts a `HoldScrollDrivenSheetActivity`, which stops momentum scrolling (if it is running).
The absence of this handling logic hasn't been problematic for simple ListViews or PageViews with only one page. This is because the SDK triggers `ScrollPosition.drag()` immediately after calling `ScrollPosition.hold()` when the user performs a press-and-hold gesture. However, in a PageView with multiple ListViews, `drag()` won't be called after `hold()` until the user actually moves their finger.
=> Fix: Press-and-hold gesture in PageView doesn't stop momentum scrolling

.github/workflows/code_check.yaml
None.
According to [dorny/test-reporter](https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories):
> Workflows triggered by pull requests from forked repositories are executed with read-only token and therefore can't create check runs. 
As a workaround, this PR modifies the workflow to generate a test report only when triggered by the original repository.
=> Don't write test report if workflow is triggered by a fork

.github/workflows/code_check.yaml
Currently, our CI pipeline only runs when `*.dart` files are modified. This PR extends the CI trigger to include changes to `pubspec.*` files, ensuring that dependency updates are also properly tested.
=> Trigger CI on pubspec.* changes

.github/actions/setup_flutter/action.yaml, .github/workflows/code_check.yaml
Closes #229.
The workflow file was updated to run unit tests and static analysis for both the lowest and highest supported Flutter SDK versions. This approach helps detect potential compatibility issues across the entire supported SDK range. For example, issue #144 stemmed from accidentally using newly added APIs in Flutter 3.22 that don't exist in lower versions, while issue #233 arose due to a breaking change introduced in Flutter 3.24.
=> Analyze and test with both lowest and highest supported Flutter SDK versions in CI

example/lib/tutorial/bottom_bar_visibility.dart, example/lib/tutorial/sheet_content_scaffold.dart, example/lib/tutorial/sheet_physics.dart, lib/src/foundation/sheet_activity.dart, lib/src/foundation/sheet_extent.dart, lib/src/foundation/sheet_physics.dart, lib/src/internal/float_comp.dart, migrations/migration-guide-0.10.x.md, test/foundation/physics_test.dart, test/foundation/sheet_activity_test.dart, test/src/matchers.dart, test/src/stubbing.dart, test/src/stubbing.mocks.dart
=> Refine settling behavior during ballistic animation

.vscode/launch.json, example/lib/tutorial/textfield_with_multiple_stops.dart, lib/src/foundation/sheet_activity.dart, lib/src/foundation/sheet_extent.dart, lib/src/foundation/sheet_physics.dart, lib/src/internal/float_comp.dart, test/foundation/physics_test.dart, test/foundation/sheet_activity_test.dart, test/foundation/sheet_viewport_test.dart, test/src/stubbing.mocks.dart
- Fixes #226
- Fixes #192 
This PR refines the `didFinalizeDimensions` method of `IdleActivity` to address the unstable behavior of the sheet when opening or closing the on-screen keyboard, as reported in #192 and #226.
=> Refine idle activity behavior during keyboard (dis)appearance

lib/src/foundation/sheet_activity.dart, test/foundation/sheet_activity_test.dart
=> Refactor activities to use SheetExtent.settleTo

example/lib/showcase/airbnb_mobile_app.dart, example/lib/tutorial/bottom_bar_visibility.dart, example/lib/tutorial/extent_driven_animation.dart, example/lib/tutorial/sheet_content_scaffold.dart, example/lib/tutorial/sheet_physics.dart, example/lib/tutorial/textfield_with_multiple_stops.dart, lib/src/foundation/sheet_physics.dart, migrations/migration-guide-0.10.x.md, test/foundation/physics_test.dart
- Rename `snapTo` to `anchors`
- Rename `snappingBehavior` to `behavior`
=> Refine snapping physics

example/pubspec.lock, lib/src/modal/modal_sheet.dart, pubspec.yaml, test/modal/modal_sheet_test.dart
Fixes #250.
This PR modifies `_SwipeDismissibleController` to ensure that the transition animation curve remains linear during the animation triggered by a swipe-to-dismiss gesture. This is crucial to prevent the sheet from jerking when the user swipes it down, as reported in #250. See the comments in the `_handleDragEnd` method for a more detailed explanation.
=> Fix: Modal sheet jerks when swipe to dismiss

example/lib/showcase/ai_playlist_generator.dart, lib/src/foundation/sheet_physics.dart, test/foundation/physics_test.dart
=> Refactor: Replace Platform (dart:io) with TargetPlatform

CHANGELOG.md, lib/src/content_scaffold.dart, pubspec.yaml, test/content_scaffold_test.dart
Fixes #312.
When using `SheetContentScaffold` with `BottomBarVisibility.always(ignoreBottomInset: true)`, the bottom bar was incorrectly hidden by the on-screen keyboard or when the sheet was scrolled partially offscreen.
This PR corrects the vertical offset calculation for the bottom bar within the `_RenderBottomBarVisibility` render object.
The root cause was that the calculation for `baseDeltaY` (the vertical translation applied to the bottom bar) did not correctly account for the `MediaQueryData.viewInsets.bottom` (keyboard height) when `ignoreBottomInset: true`. This prevented the bottom bar from translating upwards along with the sheet body as intended, causing it to be obscured by the keyboard or hidden when the sheet was partially scrolled.
=> Fix: bottom bar is hidden despite `BottomBarVisibility.always(ignoreBottomInset: true)`

lib/src/paged_sheet.dart, test/paged_sheet_test.dart
Fixes #309.
When a route within a `PagedSheet` is popped using `Navigator.pop()` while the sheet is undergoing a snapping animation (e.g., after a fling), the subsequent route transition animation starts from an incorrect offset. Instead of animating smoothly from the sheet's current position at the moment `pop()` is called, the animation uses an incorrect offset as its starting point, where the sheet was settled *before* the snapping animation began. This causes a visual jump or instability in the transition. This is particularly noticeable when popping a route during a fling-induced snap.
This PR addresses the issue by modifying the `_RouteTransitionSheetActivity`, which handles the sheet offset animation during route transitions.
1.  **Capture Current Offset:** The activity now …
=> fix: Unstable route transition in PagedSheet when pop a route during snapping animation

lib/src/paged_sheet.dart, test/paged_sheet_test.dart
Fixes #305.
When using `PagedSheet` with the `builder` parameter to construct a layout (e.g., using `SheetContentScaffold`) that includes shared elements like a top or bottom bar (`topBar`, `bottomBar`), dragging the sheet by initiating the gesture on these shared bars does not work.
The root cause is that the `PagedSheet` widget normally relies on its individual routes (`PagedSheetRoute`/`PagedSheetPage`) to wrap their content with the necessary `SheetDraggable` logic. When the `builder` is used, it inserts the shared bars *outside* the scope of the route's content, placing them visually on top. These bars then intercept the pointer events, preventing the underlying `SheetDraggable` (associated with the route's content) from receiving the drag gesture.
This PR addresses the issue by …
=> fix: PagedSheet cannot be dragged when the drag starts at shared top/bottom bar built in builder callback

.github/workflows/pr-title-lint.yml
Closes #317.
This PR introduces a GitHub Actions workflow that validates PR titles against Conventional Commits using [amannn/action-semantic-pull-request@v5](https://github.com/amannn/action-semantic-pull-request).
=> chore: Add PR title lint workflow

.github/workflows/code_check.yaml, .github/workflows/dry_publish.yaml
Closes #319.
Currently, the `code_check` and `dry_publish` workflows run validation on the `main` branch after every merge. However, due to branch protection rules, all changes to `main` must go through a pull request, and only PRs that pass validation can be merged. Therefore, running validation again on `main` after merging is redundant and consumes unnecessary resources.
This PR removes the `on: push: branches: main` trigger from the following workflow files:
- `.github/workflows/code_check.yaml`
- `.github/workflows/dry_publish.yaml`
This ensures these workflows only run on pull requests, eliminating the redundant checks on the `main` branch after merging.
=> chore: Remove redundant workflow triggers on main branch

lib/src/modal.dart, test/modal_test.dart, test/src/flutter_test_x.dart, test/src/flutter_test_x_test.dart
Closes #339.
The `SheetDismissible` widget was previously removed to simplify the API, but as highlighted in the linked issue, it's necessary for use cases where developers need finer control over the swipe-to-dismiss behavior.
This PR reintroduces the `SheetDismissible` widget.
- A `SheetDismissible` stateful widget is added back, encapsulating the swipe-to-dismiss gesture detection and animation logic previously handled internally by `ModalSheetRouteMixin`.
- The mixin now uses `SheetDismissible` internally when `swipeDismissible` is true, simplifying the mixin's own logic. It also exposes the internal `AnimationController` for `SheetDismissible` to use.
- Tests are added to verify the behavior of `SheetDismissible`, including its interaction with the `swipeDismissible` flag on …
=> feat(pkg): Reintroduce SheetDismissible

.cliffignore, lib/src/modal.dart, test/modal_test.dart
`SheetDismissible` was reintroduced in #339. However, while working on #170, we realized that the fix for #170 isn't compatible with exposing `SheetDismissible` as part of the public API. More details will be available in an upcoming PR.
Since `SheetDismissible` hasn't been published yet, this PR simply makes it a private class. We're not removing it entirely, as it will be required to address other issues like #303. Instead, users are encouraged to use `PopScope.canPop` to control the dismissibility of a modal in the build method.
=> refactor(pkg): Hide SheetDismissible from public API

lib/src/modal.dart, lib/src/model.dart, test/modal_test.dart
Fixes #170.
Dynamically changing the `swipeDismissible` property of a `ModalSheetPage` (e.g., in response to route arguments or state changes) can cause layout assertion errors.
The underlying issue is that, prior to thisPR, toggling the `swipeDismissible` flag dynamically affected the widget tree by conditionally adding or removing the `SheetGestureProxy. Since the sheet widget typically did not have a `GlobalKey`, this change in `SheetGestureProxy` presence caused the sheet's state to be lost. As a result, the following assertion errors were thrown:
1. `The sheet extent and the dimensions values must be finalized during the layout phase. 'package:smooth_sheets/src/foundation/sheet_viewport.dart': Failed assertion: line 88 pos 7: '_extent.metrics.hasDimensions'`
2. `NavigationSheet: …
=> fix(pkg): changing swipeDismissible dynamically causes a layout error

lib/src/cupertino.dart, test/cupertino_test.dart
Fixes #340.
An assertion (`!_routeToControllerMap.containsKey(route)`) failed in `_OutgoingTransitionController` when a new `CupertinoModalSheetRoute` was pushed while a previous one was still animating closed.
The issue stemmed from an assumption that there would only ever be one `_OutgoingTransitionController` per route, stored in a global map object (`_routeToControllerMap`). However, during rapid push/pop sequences, multiple `_OutgoingTransitionState` instances could be created for the same route within a single frame. This led to multiple attempts to register controllers for that route in the global map, causing the assertion failure.
This PR resolves the assertion error by refactoring the management of outgoing transitions for routes preceding a `CupertinoModalSheetRoute`:
1. …
=> fix(pkg): assertion error when push CupertinoModalSheetRoute during closing animation

lib/src/paged_sheet.dart, test/notification_test.dart
Fixes #345.
When navigating between routes within a `PagedSheet` using the `Navigator` Pages API, `SheetUpdateNotification` was not consistently dispatched during the transition animation. While the final state might eventually be reflected, listeners relying on `SheetNotification` could not observe the continuous offset changes during the route transition animation itself.
This PR ensures that `SheetUpdateNotification` is dispatched on each frame of the route transition animation within a `PagedSheet`.
=> fix(pkg): SheetNotification not dispatched during PagedSheet route transitions

lib/src/cupertino.dart, test/cupertino_test.dart
Fixes #355.
When a `CupertinoModalSheetRoute` is pushed, and the route immediately below it (the "previous route") is not a subclass of `_BaseCupertinoModalSheetRoute` (e.g., a standard `MaterialPageRoute` or `CupertinoPageRoute`), the following exception would occur if this previous route was popped *after* the modal sheet was dismissed.
```
A _OutgoingTransitionController was used after being disposed.
```
The exception happened because the `_OutgoingTransitionController` associated with this non-modal previous route was being disposed prematurely. Specifically, its `dispose` method was called when the `CupertinoModalSheetRoute` itself was disposed, rather than when the previous route it was managing was disposed.
This PR modifies how `_OutgoingTransitionController` instances are …
=> fix(pkg): Crashes when popping a non-modal sheet route just below a modal sheet route

lib/src/modal.dart, test/modal_test.dart
- Closes https://github.com/fujidaiti/smooth_sheets/issues/356
- Related to:
- https://github.com/fujidaiti/smooth_sheets/issues/346
- https://github.com/fujidaiti/smooth_sheets/issues/249#issuecomment-2822457377
Currently, while `PopScope` can influence the dismiss behavior, the swipe-to-dismiss gesture for a modal sheet is primarily controlled at the route level by `ModalSheetRoute.swipeDismissible`. This offers limited direct means to dynamically enable or disable the gesture from *within* a widget (i.e., during the `build` method of a widget inside the sheet), particularly when needing to disable the gesture and prevent the route from being popped. This limits the flexibility in scenarios where the ability to dismiss the sheet via a swipe gesture needs to change based on the internal …
=> feat(pkg): Add SheetPopScope to enable/disable the swipe gesture in modals from within build method

.github/workflows/claude_code.yaml
Attempts to fix `Integration must generate a public key` error. ([full log](https://github.com/fujidaiti/smooth_sheets/actions/runs/15507697511))
=> fix(ci): Read bot's client id from repository variables instead of secrets

lib/smooth_sheets.dart, lib/src/modal.dart, lib/src/modal_utils.dart, test/modal_utils_test.dart, test/src/test_ticker.dart
This PR introduces utility functions that simplify modal sheet usage and provide platform-adaptive behavior:
1. **`showAdaptiveModalSheet`**: Automatically selects the appropriate modal sheet based on the current platform:
- iOS/macOS: Uses `CupertinoModalSheetRoute` 
- Android/Fuchsia/Linux/Windows: Uses `ModalSheetRoute`
2. **`showModalSheet`**: Convenience function for creating and pushing `ModalSheetRoute` with sensible defaults
3. **`showCupertinoModalSheet`**: Convenience function for creating and pushing `CupertinoModalSheetRoute` with sensible defaults
- **Platform Adaptive**: `showAdaptiveModalSheet` eliminates the need for manual platform detection
- **Simplified API**: Consistent interface across all modal sheet types
- **Convenience**: Direct navigation handling without manual …
=> feat(pkg): Add utility functions to show modal sheets

.github/workflows/bump.yaml
When the `bump.yaml` workflow creates a pull request using the default `GITHUB_TOKEN`, the CI workflows do not automatically trigger for the created PR. This is a known limitation of GitHub Actions where workflows triggered by the default `GITHUB_TOKEN` do not trigger additional workflow runs to prevent infinite loops.
This means that important CI checks (tests, linting, etc.) are not executed on the version bump PRs, which could lead to merging changes without proper validation.
This PR addresses the issue by switching from the default `GITHUB_TOKEN` to a GitHub App token from the [norelease-bot](https://github.com/apps/norelease-bot) GitHub App.
1. **Generate GitHub App Token:** Added a new step to generate a token using the `actions/create-github-app-token@v1` action with the …
=> fix(ci): Use GitHub App token for version bump PRs to enable CI

.github/workflows/bump.yaml, test/src/test_ticker.dart
The current bump workflow uses `github-actions[bot]` as the commit author, which prevents the commit from triggering CI pipelines. Additionally, the workflow reads the GitHub App ID from secrets instead of variables, and doesn't automatically assign reviewers to the created PRs.
Improved the bump workflow to properly use the Norelease Bot GitHub App:
- Changed APP_ID source from secrets to variables for better security practices
- Configure Git to use dynamic Norelease Bot credentials instead of hardcoded github-actions bot
- Added proper GitHub App token authentication for all Git operations  
- Added automatic reviewer assignment to repository owner
- Made bot name and user ID dynamic using app-slug outputs from the token
This ensures version bump commits will trigger CI pipelines and …
=> fix(ci): Reland "Use GitHub App token for version bump PRs to enable CI #384"

lib/src/paged_sheet.dart, lib/src/scrollable.dart, lib/src/sheet.dart, test/scrollable_test.dart, test/src/flutter_test_x.dart, test/src/flutter_test_x_test.dart, test/src/object_ref.dart
Closes #284.
Currently, when scroll gestures are performed on scrollable content within a sheet, the sheet always takes precedence over the scrollable content when handling these gestures. This prevents the scrollable content from handling scroll gestures as intended, including overscroll-driven animations such as the bouncing effect for `BouncingScrollPhysics`.
The specific behavior requested in issue #284 requires more nuanced control: allowing the scrollable content to handle scroll gestures exclusively in certain conditions, while still maintaining the sheet's responsiveness when appropriate.
This PR introduces `SheetScrollHandlingBehavior` to control the precedence between the sheet and scrollable content when handling scroll gestures.
- **`always`**: The sheet always takes …
=> feat(pkg): Add SheetScrollHandlingBehavior for precise control over scroll gesture handling

cliff.toml
`cliff.toml` has been updated to add links to the corresponding GitHub release pages for each version section in `CHANGELOG.md`.
=> chore(ci): Add links to corresponding GitHub release pages in CHANGELOG

.github/workflows/health.yaml, example/pubspec.yaml
This PR updates the health workflow to monitor changes in the `/example` directory's `pubspec.yaml` and `pubspec.lock` files. Previously, changes to these files would not trigger the CI pipeline, potentially allowing dependency issues in the example app to go unnoticed.
- Added `example/pubspec.yaml` and `example/pubspec.lock` to the `flutter-file-changed` filter in `.github/workflows/health.yaml`
- This ensures that modifications to the example app's dependencies will trigger:
- Static analysis (dart format, dart analyze) 
- Unit tests
- Dry publish checks including pana analysis
=> feat(ci): Monitor example directory pubspec changes in health workflow

example/lib/showcase/ai_playlist_generator.dart, example/lib/tutorial/decorations.dart, example/lib/tutorial/keyboard_dismiss_behavior.dart, example/lib/tutorial/physics_and_snap_grid.dart, lib/src/cupertino.dart
This PR suppresses all `deprecated_member_use` lint warnings by adding `// ignore: deprecated_member_use` comments above the flagged lines. The deprecated APIs include:
- `RadioListTile.groupValue` and `RadioListTile.onChanged` properties (deprecated after Flutter 3.32.0)
- `Matrix4.scale()` method (deprecated in vector_math 2.2.0 / Flutter 3.35.0)
These warnings were suppressed rather than migrated to maintain compatibility until the minimum SDK version is raised to 3.35.0, as indicated by existing TODO comments in the codebase.
=> chore(pkg): Temporarily suppress deprecated_member_use warnings

.github/workflows/stale.yaml
The stale action workflow was introduced in #410 to automatically close inactive issues and PRs with the "waiting for customer response" label after 30 days of inactivity. However, the workflow configured in `.github/workflows/stale.yaml` was not functioning as intended - items were never being automatically marked as stale or closed, despite the workflow being scheduled to run weekly.
The root cause is that `days-before-stale` was set to `-1`, which disables the stale marking step entirely. The stale action requires items to first be marked as stale before they can be closed. With this step disabled, the action would never proceed to close any items, even though `days-before-close: 30` was configured.
This PR fixes the stale action configuration to properly mark and close inactive issues …
=> fix(ci): Fix stale action is not working
